# Generated by Django 5.1.7 on 2025-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['-time_create'], name='pract_goods_time_cr_887f4d_idx'),
        ),
    ]
