# Generated by Django 5.1.7 on 2025-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_alter_goods_options_goods_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
