# Generated by Django 5.1.7 on 2025-03-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_category_goods_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pract.category'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pract.supplier'),
        ),
    ]
