# Generated by Django 5.1.7 on 2025-03-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0007_supplier_alter_goods_cat_goods_sup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pract.supplier'),
        ),
    ]
