# Generated by Django 5.1.7 on 2025-03-31 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0008_alter_goods_sup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'продукция по категориям', 'verbose_name_plural': 'продукция по категориям'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['time_create'], 'verbose_name': 'Вся продукция', 'verbose_name_plural': 'Вся продукция'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'продукция по поставщикам', 'verbose_name_plural': 'продукция по поставщикам'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_cat', to='pract.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_stock',
            field=models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'Есть в наличии')], default=1, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_sup', to='pract.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Врем обновления'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Ссылка'),
        ),
    ]
